name: Discord Bot Scheduler

on:
  schedule:
    # 매일 UTC 23:50 (한국 시각 다음 날 08:50)에 실행
    - cron: "50 23 * * *"

jobs:
  run-discord-bot:
    runs-on: ubuntu-latest

    steps:
      # 1) 레포지토리 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) 파이썬 설정 (예: 3.9)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # 3) 라이브러리 설치 (requirements.txt가 있다면)
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4) 봇 실행 (20분 후 종료 예시: sleep 1200)
      - name: Run Discord Bot for 20 minutes
        run: |
          # 백그라운드로 봇 실행
          python bot.py &
          # 20분(1200초) 대기
          sleep 1200
          # "python bot.py" 프로세스를 강제 종료
          pkill -f "python bot.py"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          # 필요한 다른 키들도 추가
